Modulair Python Library: wall::gl_utils Namespace Reference
wall::gl_utils Namespace Reference
Functions
def create_app
Create an application.
def log_info
Print the message on the terminal.
def log_warn
Print a warning message on the terminal.
def log_err
Print an error message on the terminal.
def create_signal
Create a Qt signal.
def add_file_format
Add an image format to the list from which a image has to be searched.
def find_image_files
Search images in the path specified.
def load_image_files
Load image files to an array format.
def to_string
Convert image to String.
def load_video
Load video from the path.
def get_next_frame
Captures next frame in the video.
def get_video_fps
Fps of the video.
def ipl2tex
Convert image from ipl to tex format.
Variables
list default_img_file_formats = ['.jpg', '.png', '.jpeg', '.bmp']
Function Documentation
def wall.gl_utils.create_app (app_name, app_class, anonymous = True)
Create an application.
Parameters:
app_name : Application Name
app_class : Application Class Name ,e.g, widget class
anonymous : True
Returns:
app : Applicaiotn handle
app_canvas : Widget handle
def wall.gl_utils.log_info (msg)
Print the message on the terminal.
Parameters:
msg : Any type of object
def wall.gl_utils.log_warn (msg)
Print a warning message on the terminal.
Parameters:
msg : Any type of object
def wall.gl_utils.log_err (msg)
Print an error message on the terminal.
Parameters:
msg : Any type of object
Referenced by Sphere.numOfSlices(), Sphere.numOfStacks(), and Sphere.radius().
def wall.gl_utils.create_signal ()
Create a Qt signal.
Returns:
signal : QT Signal
def wall.gl_utils.add_file_format (format)
Add an image format to the list from which a image has to be searched.
Parameters:
format : File format like .png, .jpg
def wall.gl_utils.find_image_files (path, formats = None)
Search images in the path specified.
Parameters:
path : Directory to search
formats : Image formats to search for
Returns:
file_locs : File names that match the format specified
def wall.gl_utils.load_image_files (image_files)
Load image files to an array format.
Parameters:
image_files : Image file names
Returns:
images : list of array
def wall.gl_utils.to_string (image)
Convert image to String.
Referenced by Quad.set_image_texture().
def wall.gl_utils.load_video (path)
Load video from the path.
Parameters:
path : Location of the video file
Returns:
opencv video handle
def wall.gl_utils.get_next_frame (video)
Captures next frame in the video.
Parameters:
video : opencv video handle
References ipl2tex().
def wall.gl_utils.get_video_fps (video)
Fps of the video.
Parameters:
video : opencv video handle
def wall.gl_utils.ipl2tex (image)
Convert image from ipl to tex format.
Parameters:
image : image in iple format
Returns:
outimage : Image in tex format
Referenced by get_next_frame().
Variable Documentation
list default_img_file_formats = ['.jpg', '.png', '.jpeg', '.bmp']